ame: Github Actions CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Compile Slides
      uses: xu-cheng/latex-action@master
      with:
        root_file: main.tex
        working_directory: slides
    - name: Compile Example
      uses: xu-cheng/latex-action@master
      with:
        root_file: main.tex
        working_directory: example
    - name: Check pdf files
      run: |
        file slides/main.pdf | grep -q ' PDF '
        file example/main.pdf | grep -q ' PDF '
    - name: Upload
      run: |
        # configure git
        git config --global user.name "Cheng XU"
        git config --global user.email "git@xuc.me"

        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

        git clone --depth=1 --branch gh-pages git@github.com:xu-cheng/latex-tutorial.git "$GITHUB_WORKSPACE/deploy"
        cp -f slides/main.pdf "$GITHUB_WORKSPACE/deploy/slides.pdf"
        cp -f example/main.pdf "$GITHUB_WORKSPACE/deploy/example.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git add slides.pdf example.pdf
        git commit -m "[github actions] deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
